
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

#jpa
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
#redis
data:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
#spring mail
mail:
  host: smtp.gmail.com
  port: ${MAIL_PORT}
  username: ${MAIL_ID}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
